spring:
  datasource:
    username: root
    password: qlqjs123
    url: jdbc:log4jdbc:mysql://localhost:3306/test
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        #        fromat_sql: true
        #        show_sql: true
        default_batch_fetch_size: 500
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

    open-in-view: false