spring:
  datasource:
    username: root
    password: qlqjs123
    url: jdbc:log4jdbc:mysql://localhost:3306/test
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        #        fromat_sql: true
        #        show_sql: true
        default_batch_fetch_size: 500
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

    open-in-view: false

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 560467275639-elcqorktg90em5boebl5ukrlh6of1c4k.apps.googleusercontent.com
            client-secret: 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
            scope: email, profile

app:
  auth:
    tokenSecret: aiden
    tokenExpirationMsec: 864000000
  oauth2:
    authorizedRedirectUris:
     - http://localhost:8080/oauth2/redirect
     - http://localhost:3000/oauth2/redirect