spring:
  profiles:
    active: local
server:
  port: 8080
  tomcat:
    basedir: ./
    accesslog:
      enabled: true
      pattern: "%t %a %s \"%r\" %b (%D ms)"
      directory: logs
      suffix: .log
      prefix: access